-- Migration: 001_campus_mode
-- Adds Campus Mode support for Pro/Enterprise churches that want to
-- link existing church accounts together without creating new accounts.
--
-- campus_id       — NULL for main/standalone campuses; points to the main campus
--                   churchId when this church is a satellite in a campus group.
--                   Self-referencing FK: REFERENCES churches(churchId).
--
-- campus_link_code — 6-character uppercase code generated by the main campus.
--                    Satellites enter this code to join the campus group.
--                    Must be unique across all churches.
--
-- This is separate from parent_church_id (used by the reseller/admin-created
-- campus flow). Campus Mode is the self-service equivalent for Pro/Enterprise
-- churches that manage their own linking without going through a reseller.

ALTER TABLE churches ADD COLUMN campus_id TEXT;
ALTER TABLE churches ADD COLUMN campus_link_code TEXT;

CREATE INDEX IF NOT EXISTS idx_churches_campus_id ON churches(campus_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_churches_campus_link_code ON churches(campus_link_code);
