module.exports = [
  {
    ignores: [
      'node_modules/**',
      '.claude/**',
      'data/**',
      'coverage/**',
      'public/**',
      'public/admin/assets/**',
      'admin/node_modules/**',
    ],
  },
  {
    files: ['**/*.js'],
    ignores: ['admin/**/*.js', 'tests/**/*.js', '**/*.test.js', 'vitest.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Buffer: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        __dirname: 'readonly',
        clearImmediate: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        crypto: 'readonly',
        fetch: 'readonly',
        global: 'readonly',
        module: 'writable',
        process: 'readonly',
        require: 'readonly',
        setImmediate: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-constant-condition': 'warn',
      'no-dupe-keys': 'error',
      eqeqeq: ['warn', 'always'],
      'no-throw-literal': 'warn',
    },
  },
  {
    files: ['tests/**/*.js', '**/*.test.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        afterAll: 'readonly',
        afterEach: 'readonly',
        Buffer: 'readonly',
        clearInterval: 'readonly',
        clearImmediate: 'readonly',
        clearTimeout: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        console: 'readonly',
        describe: 'readonly',
        expect: 'readonly',
        fetch: 'readonly',
        global: 'readonly',
        it: 'readonly',
        module: 'readonly',
        process: 'readonly',
        require: 'readonly',
        setInterval: 'readonly',
        setImmediate: 'readonly',
        setTimeout: 'readonly',
        URL: 'readonly',
        vi: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-constant-condition': 'warn',
      'no-dupe-keys': 'error',
      eqeqeq: ['warn', 'always'],
      'no-throw-literal': 'warn',
    },
  },
  {
    files: ['vitest.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-constant-condition': 'warn',
      'no-dupe-keys': 'error',
      eqeqeq: ['warn', 'always'],
      'no-throw-literal': 'warn',
    },
  },
  {
    files: ['admin/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        URL: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-constant-condition': 'warn',
      'no-dupe-keys': 'error',
      eqeqeq: ['warn', 'always'],
      'no-throw-literal': 'warn',
    },
  },
];
