// @ts-check
/**
 * Shared helpers for the portal-e2e provisioning scripts.
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..', '..');
const PORTAL_E2E_DIR = path.resolve(__dirname, '..');
const ENV_FILE = path.join(PORTAL_E2E_DIR, '.env');
const PROVISIONED_ENV_FILE = path.join(PORTAL_E2E_DIR, '.env.provisioned');
const STATE_FILE = path.join(PORTAL_E2E_DIR, '.provisioned.json');

const TEST_PREFIX = 'e2e-test';

function loadDotenvFile(file) {
  if (!fs.existsSync(file)) return {};
  const raw = fs.readFileSync(file, 'utf8');
  const out = {};
  for (const rawLine of raw.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function loadEnv() {
  // .env.provisioned overrides .env so a fresh provisioning always wins.
  return { ...loadDotenvFile(ENV_FILE), ...loadDotenvFile(PROVISIONED_ENV_FILE) };
}

function writeProvisionedEnv(values) {
  const banner = [
    '# AUTO-GENERATED by portal-e2e/scripts/provision.js',
    '# Do not edit by hand. This file is overwritten on each provisioning run',
    '# and removed by deprovision / global teardown.',
    '',
  ].join('\n');
  const body = Object.entries(values)
    .map(([k, v]) => `${k}=${v}`)
    .join('\n');
  fs.writeFileSync(PROVISIONED_ENV_FILE, banner + body + '\n', 'utf8');
}

function removeProvisionedEnv() {
  if (fs.existsSync(PROVISIONED_ENV_FILE)) fs.unlinkSync(PROVISIONED_ENV_FILE);
}

function readState() {
  if (!fs.existsSync(STATE_FILE)) return null;
  try {
    return JSON.parse(fs.readFileSync(STATE_FILE, 'utf8'));
  } catch {
    return null;
  }
}

function writeState(state) {
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2) + '\n', 'utf8');
}

function removeState() {
  if (fs.existsSync(STATE_FILE)) fs.unlinkSync(STATE_FILE);
}

function generatePassword() {
  // 32-char alphanumeric, well above the 8-char minimum.
  return require('node:crypto').randomBytes(24).toString('base64url');
}

function generateUniqueSuffix() {
  const ts = Date.now();
  const rand = require('node:crypto').randomBytes(4).toString('hex');
  return `${ts}-${rand}`;
}

function buildTestAccount(emailDomain) {
  const suffix = generateUniqueSuffix();
  // Plus-addressing keeps every test account deliverable to the same inbox
  // while remaining unique. Adjust by setting PORTAL_E2E_EMAIL_DOMAIN.
  const domain = emailDomain || 'tallyconnect.app';
  const localBase = process.env.PORTAL_E2E_EMAIL_USER || TEST_PREFIX;
  const email = `${localBase}+${suffix}@${domain}`;
  const name = `E2E Test Church ${suffix}`;
  const password = generatePassword();
  return { email, name, password, suffix };
}

async function callRelay(baseUrl, method, path, { body, adminApiKey, headers } = {}) {
  const url = new URL(path, baseUrl).toString();
  const allHeaders = {
    'Content-Type': 'application/json',
    ...(adminApiKey ? { 'x-api-key': adminApiKey } : {}),
    ...(headers || {}),
  };
  const res = await fetch(url, {
    method,
    headers: allHeaders,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  let parsed = text;
  try { parsed = JSON.parse(text); } catch { /* keep raw */ }
  return { status: res.status, ok: res.ok, body: parsed };
}

module.exports = {
  ROOT,
  PORTAL_E2E_DIR,
  ENV_FILE,
  PROVISIONED_ENV_FILE,
  STATE_FILE,
  TEST_PREFIX,
  loadEnv,
  loadDotenvFile,
  writeProvisionedEnv,
  removeProvisionedEnv,
  readState,
  writeState,
  removeState,
  generatePassword,
  generateUniqueSuffix,
  buildTestAccount,
  callRelay,
};
